--PKG ALUNO--
CREATE OR REPLACE PACKAGE PKG_ALUNO AS
  PROCEDURE EXCLUIR_ALUNO(p_id_aluno IN NUMBER);
  CURSOR CURSOR_ALUNOS_MAIORES IS
    SELECT NOME, DATA_NASCIMENTO
    FROM ALUNOS
    WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM DATA_NASCIMENTO) > 18;
  CURSOR CURSOR_ALUNOS_POR_CURSO(p_id_curso IN NUMBER) IS
    SELECT NOME
    FROM ALUNOS A
    INNER JOIN MATRICULAS M ON A.ID = M.ID_ALUNO
    WHERE M.ID_CURSO = p_id_curso;
END PKG_ALUNO;
/
CREATE OR REPLACE PACKAGE BODY PKG_ALUNO AS
  PROCEDURE EXCLUIR_ALUNO(p_id_aluno IN NUMBER) IS
  BEGIN
    DELETE FROM MATRICULAS WHERE ID_ALUNO = p_id_aluno;
    DELETE FROM ALUNOS WHERE ID = p_id_aluno;
    COMMIT;
  END EXCLUIR_ALUNO;
END PKG_ALUNO;
/

--PKG DISCIPLINA--
CREATE OR REPLACE PACKAGE PKG_DISCIPLINA AS
  PROCEDURE CADASTRAR_DISCIPLINA(p_nome IN VARCHAR2, p_descricao IN VARCHAR2, p_carga_horaria IN NUMBER);
  CURSOR CURSOR_TOTAL_ALUNOS_DISC IS
    SELECT D.NOME, COUNT(*) AS TOTAL_ALUNOS
    FROM DISCIPLINAS D
    INNER JOIN MATRICULAS M ON D.ID = M.ID_DISCIPLINA
    GROUP BY D.NOME
    HAVING COUNT(*) > 10;
  CURSOR CURSOR_MEDIA_IDADE_DISC(p_id_disciplina IN NUMBER) IS
    SELECT AVG(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM A.DATA_NASCIMENTO)) AS MEDIA_IDADE
    FROM ALUNOS A
    INNER JOIN MATRICULAS M ON A.ID = M.ID_ALUNO
    WHERE M.ID_DISCIPLINA = p_id_disciplina;
END PKG_DISCIPLINA;
/
CREATE OR REPLACE PACKAGE BODY PKG_DISCIPLINA AS
  PROCEDURE CADASTRAR_DISCIPLINA(p_nome IN VARCHAR2, p_descricao IN VARCHAR2, p_carga_horaria IN NUMBER) IS
  BEGIN
    INSERT INTO DISCIPLINAS (NOME, DESCRICAO, CARGA_HORARIA)
    VALUES (p_nome, p_descricao, p_carga_horaria);
    COMMIT;
  END CADASTRAR_DISCIPLINA;
END PKG_DISCIPLINA;
/

-- Criação do pacote PKG_PROFESSOR--
CREATE OR REPLACE PACKAGE PKG_PROFESSOR AS
  CURSOR CURSOR_TURMAS_PROF IS
    SELECT P.NOME, COUNT(*) AS TOTAL_TURMAS
    FROM PROFESSORES P
    INNER JOIN TURMAS T ON P.ID = T.ID_PROFESSOR
    GROUP BY P.NOME
    HAVING COUNT(*) > 1;
  FUNCTION TOTAL_TURMAS_PROFESSOR(p_id_professor IN NUMBER) RETURN NUMBER;
  FUNCTION NOME_PROFESSOR_DISCIPLINA(p_id_disciplina IN NUMBER) RETURN VARCHAR2;
END PKG_PROFESSOR;
/
CREATE OR REPLACE PACKAGE BODY PKG_PROFESSOR AS
  FUNCTION TOTAL_TURMAS_PROFESSOR(p_id_professor IN NUMBER) RETURN NUMBER IS
    v_total NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_total
    FROM TURMAS
    WHERE ID_PROFESSOR = p_id_professor;
    RETURN v_total;
  END TOTAL_TURMAS_PROFESSOR;

  FUNCTION NOME_PROFESSOR_DISCIPLINA(p_id_disciplina IN NUMBER) RETURN VARCHAR2 IS
    v_nome VARCHAR2(100);
  BEGIN
    SELECT P.NOME INTO v_nome
    FROM PROFESSORES P
    INNER JOIN DISCIPLINAS D ON P.ID = D.ID_PROFESSOR
    WHERE D.ID = p_id_disciplina;
    RETURN v_nome;
  END NOME_PROFESSOR_DISCIPLINA;
END PKG_PROFESSOR;
/
